/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Base64Tool: typeof import('./src/components/tools/base64-tool/base64-tool.vue')['default']
    CompressConfigBox: typeof import('./src/components/compress-config-box/compress-config-box.vue')['default']
    CompressTool: typeof import('./src/components/tools/compress-tool/compress-tool.vue')['default']
    CopyImageLink: typeof import('./src/components/copy-image-link/copy-image-link.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FolderCard: typeof import('./src/components/folder-card/folder-card.vue')['default']
    GettingImages: typeof import('./src/components/getting-images/getting-images.vue')['default']
    HeaderContent: typeof import('./src/components/header-content/header-content.vue')['default']
    ImageCard: typeof import('./src/components/image-card/image-card.vue')['default']
    ImageLinkRuleConfig: typeof import('./src/components/image-link-rule-config/image-link-rule-config.vue')['default']
    ImageSelector: typeof import('./src/components/image-selector/image-selector.vue')['default']
    ImgProcessStateCard: typeof import('./src/components/tools/img-process-state-card/img-process-state-card.vue')['default']
    MainContainer: typeof import('./src/components/main-container/main-container.vue')['default']
    NavContent: typeof import('./src/components/nav-content/nav-content.vue')['default']
    RefreshConfig: typeof import('./src/components/refresh-config/refresh-config.vue')['default']
    RepoDirCascader: typeof import('./src/components/repo-dir-cascader/repo-dir-cascader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectedInfoBar: typeof import('./src/components/selected-info-bar/selected-info-bar.vue')['default']
    SiteCount: typeof import('./src/components/site-count/site-count.vue')['default']
    ToUploadImageCard: typeof import('./src/components/to-upload-image-card/to-upload-image-card.vue')['default']
    UploadArea: typeof import('./src/components/upload-area/upload-area.vue')['default']
    WatermarkConfigBox: typeof import('./src/components/watermark-config-box/watermark-config-box.vue')['default']
    WatermarkTool: typeof import('./src/components/tools/watermark-tool/watermark-tool.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
