// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CopyExternalLink: typeof import('./src/components/copy-external-link/copy-external-link.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FolderCard: typeof import('./src/components/folder-card/folder-card.vue')['default']
    HeaderContent: typeof import('./src/components/header-content/header-content.vue')['default']
    ImageCard: typeof import('./src/components/image-card/image-card.vue')['default']
    ImageSelector: typeof import('./src/components/image-selector/image-selector.vue')['default']
    ImageViewer: typeof import('./src/components/image-viewer/image-viewer.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MainContainer: typeof import('./src/components/main-container/main-container.vue')['default']
    NavContent: typeof import('./src/components/nav-content/nav-content.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectedInfoBar: typeof import('./src/components/selected-info-bar/selected-info-bar.vue')['default']
    SiteCount: typeof import('./src/components/site-count/site-count.vue')['default']
    Step1: typeof import('./src/components/tutorials-step/step1.vue')['default']
    Step2: typeof import('./src/components/tutorials-step/step2.vue')['default']
    Step3: typeof import('./src/components/tutorials-step/step3.vue')['default']
    ToUploadImageCard: typeof import('./src/components/to-upload-image-card/to-upload-image-card.vue')['default']
    UploadArea: typeof import('./src/components/upload-area/upload-area.vue')['default']
  }
}

export {}
