export const PICX_REPO_NAME = 'picx-images-hosting'
export const PICX_REPO_DESC = 'PicX images hosting repository'
export const PICX_REPO_INIT_BARNCH = 'master'
export const PICX_UPLOAD_IMG_DESC = 'Upload image via PicX(https://github.com/XPoet/picx)'
export const PICX_UPLOAD_IMGS_DESC = 'Upload images via PicX(https://github.com/XPoet/picx)'
export const PICX_DEL_IMG_DESC = 'Delete image via PicX(https://github.com/XPoet/picx)'
