const PICX_PREFIX = 'PICX_'

export const LS_PICX_CONFIG = `${PICX_PREFIX}CONFIG`
export const LS_PICX_MANAGEMENT = `${PICX_PREFIX}MANAGEMENT`
export const LS_PICX_SETTINGS = `${PICX_PREFIX}SETTINGS`
export const SS_PICX_UPLOADED = `${PICX_PREFIX}UPLOADED`
